name: Run Selenium Automation

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the start of the hour

jobs:
  run-selenium:
    runs-on: ubuntu-latest  # Use a free GitHub Actions runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out your repository

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'  # Use Java 21 (as specified in your pom.xml)
        distribution: 'temurin'  # Use Eclipse Temurin JDK

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        

    - name: Run Selenium Automation
      run: |
        mvn compile  # Compile your Java code
        mvn exec:java -Dexec.mainClass="org.example.Main"  # Run your main class
